### ISSUE TITLE
Add options for Link Dialers

### ISSUE THREAD

**Issue by emoscardini** [netfoundry/ziti_router_auto_enroll#6]
```
link:
  dialers:
    - binding: transport
      options:
        connectTimeoutMs: 10000
```
